name: 'Blues Mandolin '
favicon: null
layout_spectrum: 0.6529182123485953
typography_spectrum: 0.6315467460080981
title: 'Bert Deivert - Roots Blues Mandolin '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffea30'
    - '#ff4717'
    - '#8e1406'
    - '#767676'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.14895887323655188
  rhythmicContrast: 0.25
purpose: []
