name: 'Blues Mandolin '
favicon: null
layout_spectrum: 0.6529182123485953
typography_spectrum: 0.6315467460080981
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4224717391189188
  lightness: 0.9721037794370204
  saturation: 0.14895887323655188
  rhythmicContrast: 0.14950142242014408
purpose: []
